version: '3.7'

services:
  jupyter:
    image: ${DOCKER_REGISTRY:-itisfoundation}/maintenance-jupyter:${DOCKER_IMAGE_TAG:-latest}
    init: true
    build:
      context: ./jupyter
      dockerfile: Dockerfile
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
    ports:
      - 8888
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - maintenance_data:/home/jovyan/work/data
    networks:
      - simcore_default

networks:
  simcore_default:
    external: true


volumes:
  maintenance_data: {}