version: '3.7'
services:
  adminer:
    image: adminer
    init: true
    ports:
      - 8080
    networks:
      - monitored
      - public
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=${PUBLIC_NETWORK}
        - traefik.http.services.adminer.loadbalancer.server.port=8080
        - traefik.http.routers.adminer.rule=PathPrefix(`/adminer`)
        - traefik.http.routers.adminer.entrypoints=https
        - traefik.http.routers.adminer.tls=true
        # Let's encrypt use case
        # - traefik.http.routers.adminer.tls.certresolver=myhttpchallenge
        - traefik.http.middlewares.adminer_stripprefixregex.stripprefixregex.regex=^/adminer
        - traefik.http.routers.adminer.middlewares=gzip_compress@file, adminer_stripprefixregex
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

networks:
  public:
    external: true
    name: ${PUBLIC_NETWORK}
  monitored:
    name: ${MONITORED_NETWORK}
    external: true
