version: '3.7'
services:
  adminer:
    image: adminer
    init: true
    # ports:
    #   - 8080
    networks:
      - simcore_default
      - public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=${PUBLIC_NETWORK}
        - traefik.http.services.adminer.loadbalancer.server.port=8080
        - traefik.http.routers.adminer.rule=PathPrefix(`/adminer`)
        - traefik.http.routers.adminer.entrypoints=https
        - traefik.http.routers.adminer.tls=true
        - traefik.http.middlewares.adminer_replace_regex.replacepathregex.regex=^/portainer/?(.*)$$
        - traefik.http.middlewares.adminer_replace_regex.replacepathregex.replacement=/$${1}
        - traefik.http.routers.adminer.middlewares=gzip_compress@file, adminer_replace_regex

networks:
  simcore_default:
    external: true
  public:
    external: true
    name: ${PUBLIC_NETWORK}
