version: '3.7'
services:
  adminer:
    image: adminer
    init: true
    # ports:
    #   - 8080
    networks:
      - simcore_default
      - public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.http.services.adminer.loadbalancer.server.port=8080
        - traefik.http.routers.adminer.rule=Host(`${MACHINE_FQDN}`)
        - traefik.http.routers.adminer.entrypoints=adminer
        - traefik.http.routers.adminer.tls=true
        - traefik.http.routers.adminer.middlewares=gzip_compress@file

        # force https
        - traefik.http.middlewares.adminer_force_https.redirectScheme.scheme=https
        - traefik.http.middlewares.adminer_force_https.redirectScheme.port=18000
        - traefik.http.routers.adminer_http.rule=Host(`${MACHINE_FQDN}`)
        - traefik.http.routers.adminer_http.entrypoints=adminer
        - traefik.http.routers.adminer_http.middlewares=adminer_force_https

networks:
  simcore_default:
    external: true
  public:
    external: true
