version: "3.6"
services:
  auto-deployment-agent:
    build:
      target: development
    image: deployment-agent:dev
    volumes:
      - ./deployment-agent:/devel/services/deployment-agent
