version: "3.6"
services:
  auto-deployment-agent:
    build:
      context: ./deployment-agent
      dockerfile: Dockerfile
      target: production
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "https://github.com/ITISFoundation/osparc-simcore"
        org.label-schema.vcs-ref: "${VCS_REF}"
      args:
        - DOCKER_GID_ARG=${DOCKER_GID:?Undefined docker gid in host}
    image: deployment-agent:latest
    ports:
      - "8888:8888"
    configs:
      - source: deployment_config
        target: /home/scu/config-prod.yaml
    environment:
      GITLAB_USERNAME: ${GITLAB_USERNAME}
      GITLAB_PASSWORD: ${GITLAB_PASSWORD}
      RUN_DOCKER_ENGINE_ROOT: ${RUN_DOCKER_ENGINE_ROOT}
    networks:
      - agent_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    command: --admin-password ${DOCKER_ADMIN_PWD} -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:

configs:
  deployment_config:
    file: ./deployment_config.yaml
