version: '3.7'
services:
  portainer:
    dns: # Sometimes the DNS from the AWS AMI are not properly copied into the container and the container canno't acces internet
      8.8.8.8
    deploy:
      labels:
        - traefik.http.routers.redis.tls=false
        - traefik.http.routers.redis.entrypoints=http
