version: '3.7'

services:
  reverse-proxy:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    init: true
    command: >
          --api=true
          --api.dashboard=true
          --api.insecure=true
          --log.level="INFO"
          --accesslog=true
          --metrics.prometheus=true
          --metrics.prometheus.addEntryPointsLabels=true
          --metrics.prometheus.addServicesLabels=true
          --entryPoints.metrics.address=":8082"
          --metrics.prometheus.entryPoint="metrics"
          --entryPoints.http.address=":80"
          --entryPoints.https.address=":443"
          --entryPoints.storage.address=":10000"
          --providers.docker.endpoint="unix:///var/run/docker.sock"
          --providers.docker.swarmMode=true
          --providers.docker.exposedByDefault=false
          --providers.file.filename="/etc/traefik/dynamic_conf.yml"

    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host      
      - target: 10000
        published: 10000
        mode: host

      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: traefik_dynamic_config.yml
        target: /etc/traefik/dynamic_conf.yml
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=Host(`${MACHINE_FQDN}`) && PathPrefix(`/dashboard`)
        - traefik.http.routers.traefik.entrypoints=https
        - traefik.http.routers.traefik.tls=true
        - traefik.http.routers.traefik.middlewares=gzip_compress@file
        - traefik.http.services.traefik.loadbalancer.server.port=8080
        - traefik.docker.network=public
    secrets:
      - domain.key
      - domain.crt
    networks:
      - public

configs:
  traefik_dynamic_config.yml:
    file: ./config/dynamic_conf.yml

secrets:
  domain.key:
    file: ./secrets/domain.key
  domain.crt:
    file: ./secrets/domain.crt

networks:
  public:
    driver: overlay
    name: public
