tls:
  certificates:
  - certFile: /run/secrets/domain.crt
    keyFile: /run/secrets/domain.key
    stores:
    - default
  stores:
    defaultCertificate:
      certFile: /run/secrets/domain.crt
      keyFile: /run/secrets/domain.key

