tls:
  certificates:
  - certFile: /run/secrets/domain.crt
    keyFile: /run/secrets/domain.key
    stores:
    - default
  # options:
  #   default:
  #     clientAuth:
  #       caFiles:
  #       - /run/secrets/rootca.crt
  #       clientAuthType: RequireAndVerifyClientCert
