version: '3.7'

services:
  agent:
    image: portainer/agent
    init: true
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    init: true
    command: >
      -H tcp://tasks.agent:9001 --tlsskipverify
      --admin-password-file /run/secrets/portainer_admin_password
    ports:
      - "8000:8000"
      # - "9000:9000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      - public
    secrets:
      - portainer_admin_password
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.http.services.portainer.loadbalancer.server.port=9000
        - traefik.http.routers.portainer.rule=Host(`${MACHINE_FQDN}`)
        - traefik.http.routers.portainer.entrypoints=portainer
        - traefik.http.routers.portainer.tls=true
        - traefik.http.routers.portainer.middlewares=gzip_compress@file

        # force https
        - traefik.http.middlewares.portainer_force_https.redirectScheme.scheme=https
        - traefik.http.middlewares.portainer_force_https.redirectScheme.port=9000
        - traefik.http.routers.portainer_http.rule=Host(`${MACHINE_FQDN}`)
        - traefik.http.routers.portainer_http.entrypoints=portainer
        - traefik.http.routers.portainer_http.middlewares=portainer_force_https

networks:
  agent_network:
    driver: overlay
    attachable: true
  public:
    external: true

volumes:
  portainer_data:

secrets:
  portainer_admin_password:
    external: true
