## Runtime configuration for the simcore_service_deployment_agent application.
##
version: '1.0'
rest:
  version: v0
  location: oas3/v0/openapi.yaml
main:
  log_level: DEBUG
  host: 127.0.0.1
  port: 8888
  watched_git_repositories:
    - id: github-simcore
      url: https://github.com/ITISFoundation/osparc-simcore.git
      branch: master
      pull_only_files: false
      paths: 
        - services/docker-compose.yml    
  docker_private_registries:
    - url: https://index.docker.io/v1
      username: some-user
      password: ""
  docker_stack_recipe:
    files: []
    workdir: github-simcore
    command: make create-staging-stack-file output_file=stack.yml
    stack_file: stack.yml
  portainer:
    - url: http://localhost:9000
      username: admin
      password: adminadmin
      stack_name: services
  excluded_services: [webclient]
  excluded_volumes: []
  polling_interval: 30
  notifications:    
      - service: mattermost
        url: mattermost_url
        message: "[A new staging version of oSparc has been deployed !!!](the_url_to_go_for/)"
        enabled: true
        channel_id: drkzbuy6c7yhjbsdr8mj3yrsyr
        personal_token: some_token