version: "3.7"

services:
  portus:
    extra_hosts:
      - "${MACHINE_FQDN}:${MACHINE_IP}"
    deploy:
      labels:
        - traefik.http.routers.portus.entrypoints=portus
        - traefik.http.routers.portus_token.entrypoints=portus

  registry:
    environment:
      # set to true if using self-signed certificates
      UPDATE_CERTIFICATES: "true"
    deploy:
      labels:
        - traefik.http.routers.registry.entrypoints=portus
    extra_hosts:
      - "${MACHINE_FQDN}:${MACHINE_IP}"
    secrets:
      - source: domain.key
        target: /secrets/domain.key
      - source: domain.crt
        target: /secrets/domain.crt
      - source: rootca.crt
        target: /secrets/rootca.crt

secrets:
  # private key
  domain.key:
    external: true
  # certificate
  domain.crt:
    external: true
  # root authority
  rootca.crt:
    external: true
