version: "3.7"

services:
  portus:
    deploy:
      labels:
        - traefik.http.routers.portus.tls.certresolver=lehttpchallenge
        - traefik.http.routers.portus_token.tls.certresolver=lehttpchallenge

  registry:
    deploy:
      labels:
        - traefik.http.routers.registry.tls.certresolver=lehttpchallenge
