version: "3.7"

services:
  portus:
    deploy:
      labels:
        - traefik.http.routers.portus.tls.certresolver=lehttpchallenge
        - traefik.http.routers.portus_token.tls.certresolver=lehttpchallenge
    extra_hosts:
      - "${MACHINE_FQDN}:${MACHINE_IP}"
  background:
    extra_hosts:
      - "${MACHINE_FQDN}:${MACHINE_IP}"

  registry:
    deploy:
      labels:
        - traefik.http.routers.registry.tls.certresolver=lehttpchallenge
    extra_hosts:
      - "${S3_ENDPOINT}:${S3_ENDPOINT_IP}"
