version: '3.7'
services:
  prometheus:
    command:
      - '--web.external-url=https://${MONITORING_DOMAIN}/prometheus/'
    deploy:
      labels:
        - traefik.http.routers.prometheus.tls.certresolver=lehttpchallenge

  grafana:
    deploy:
      labels:
        # direct access through port
        - traefik.http.routers.grafana.tls.certresolver=lehttpchallenge
